### PR TITLE
Fix for issue #71

### LINKED ISSUE #71: Smoothing in different areas
When smoothing globally, there might be some areas that need intensive smoothing and some others that do not need to be intensive. As an example, passive margins would need several rounds of smoothing to make the difference between deep ocean and the land minimal. To solve this, we may introduce smoothing by masks. For this the smoothing tool should have an option to introduce the masks file. And each mask can have its own smoothing parameters, such as the radius in pixels to consider while smoothing. Also, the smoothing tool is too slow. There should be different approaches for smoothing. Need to explore smoothing techniques.

### PR DESCRIPTION
**Pull request by jaminzoda**
Smoothing is improved to allow constraining the smoothing area and wrapping at date line. 
Changes:

1. Now the smoothing tool accepts a mask layer to smooth inside mask polygons only. Smoothing factor can be different for each polygon and can be retrieved from the attribute table via the property override button beside the smoothing factor spinbox.
2. Handle the boundaries automatically. It first checks if the raster covers the entire globe. If so, it wraps the raster at the boundary to the opposite side. 
3. Polygon masks that are outside the extent of the raster layer, they are adjusted to not go beyond the raster layer. So, now if one wants to smooth raster at its edges, he/she can draw any polygon without a fear to outside the raster extent.
Close #71

### CODE REVIEW

**Comment by Diego635** [comment]
Tested.
No bugs
Works fine, but needs discussion about some aspects of the functionality

**Comment by Diego635** [comment]
I must update the corresponding page of the manual. There are some important changes to this tool.

**Comment by jaminzoda** [comment]
Before merging this PR, need first to merge #140 into it.

**Comment by Diego635** [comment]
Once all other conflicts are resolved, the version chosen for the merge will have to be **1.1-RC.2**

**Comment by Diego635** [comment]
@jaminzoda  Before merging these issues have to be addressed: #229 and #230

**Comment by Diego635** [comment]
There is an error when loading this in QGIS:

> Couldn't load plugin 'terra_antiqua' due to an error when calling its classFactory() method 
> 
> SyntaxError: invalid syntax 
> Traceback (most recent call last):
>   File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/__init__.py", line 35, in classFactory
>     from .core.terra_antiqua import TerraAntiqua
>   File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/core/terra_antiqua.py", line 60, in 
>     from ..gui.standard_proc_dlg import  TaStandardProcessingDlg
>   File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/standard_proc_dlg.py", line 16
>     from qgis.gui import QgsSpinBox
>        ^
> SyntaxError: invalid syntax
> 
> 
> Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
> QGIS version: 3.10.14-A Coruña A Coruña, 8374282d2a 
> 
> Python Path:
> /Applications/QGIS3.10.app/Contents/MacOS/../Resources/python
> /Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python
> /Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
> /Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins
> /Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
> /Applications/QGIS3.10.app/Contents/Resources/python
> /Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
> /Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
> /Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
> /Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
> /Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python
> /Users/diego/Downloads/TA_sample_data_bundle

**Comment by Diego635** [comment]
@jaminzoda 
Now the Std proc dialog is not changing when I select 1 option in the spinbox. It shows all fields from all tools and doesn't hide the ones that don't correspond to the tool I selected, as it should do.
The help text is changing correctly, though.

**Pull request merged**
